### ISSUE TITLE
не работает ## not work

### ISSUE THREAD

**Issue by sashka3076** [Bafomet666/Bigbro#8]
└──╼ #sudo python3 brother.py
Traceback (most recent call last):
  File "/root/Bigbro/brother.py", line 8, in <module>
    from utils.banner import show_banner
ModuleNotFoundError: No module named 'utils.banner'; 'utils' is not a package

**Comment by YardGitBomber** [comment]
в ошибке написано же, что нет пакета "utils" попробуй установить его

**Comment by Bafomet666** [comment]
Ближе к 10 числу, клиент будет обновлен. Много изменений, баги, недоработки уйдут

**Comment by Bafomet666** [comment]
Пока можешь использовать эту версию 

https://github.com/Bafomet666/OSINT-SAN

**Comment by Bafomet666** [comment]
Клиент обновлен

**Comment by Bafomet666** [comment]
> в ошибке написано же, что нет пакета "utils" попробуй установить его

Это не пакет. Клиент обновил, фикс внесен
